// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/a/[slug].tsx";
import * as $1 from "./routes/api/posts.ts";
import * as $2 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/a/[slug].tsx": $0,
    "./routes/api/posts.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
